name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set build tag
      run: |
        echo "BUILD_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker login -u=wzhao18 -p=${{ secrets.DOCKER_REGISTRY_TOKEN }} docker.io
        docker build . --file Dockerfile --tag tally:$BUILD_TAG

    - name: Run tests
      run: |
        docker run --shm-size=24g --rm tally:$BUILD_TAG ./run_test.sh
      
    - name: Clean up
      if: always()
      run: |
        docker rmi tally:$BUILD_TAG -f